user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;

    # Serveur Nginx pour l'application Angular
    server {
        listen 3000;
        server_name localhost;

        # Répertoire où se trouve le build Angular (le dossier browser après build)
        root /usr/share/nginx/html/browser;

        # Fichier par défaut
        index index.html;

        # Redirection des requêtes Angular vers index.html sauf si un fichier statique existe
        location / {
            try_files $uri $uri/ /index.html;
            index index.html;
        }

        # Gestion des erreurs 404 avec une page 404 personnalisée
        error_page 404 /404.html;
        location = /404.html {
            root /usr/share/nginx/html;  # Assurez-vous que la page 404.html est générée par Angular ou manuellement incluse
            internal;
        }

        # Gérer le cache des fichiers statiques pour améliorer les performances
        location ~* \.(?:manifest|appcache|html?|xml|json)$ {
            expires -1;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        }

        location ~* \.(?:css|js|woff2?|eot|ttf|otf|svg|gif|ico|jpg|jpeg|png)$ {
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }
    }
}
